"""Provider interfaces for local LLM usage."""

from __future__ import annotations

from typing import Protocol


class LLMError(RuntimeError):
    """Raised when a local LLM provider cannot return a valid response."""


class LLMProvider(Protocol):
    name: str
    model: str

    def chat_json(self, system: str, user: str, timeout: int = 60) -> dict:
        """Return a JSON object generated by the provider."""
